### ISSUE TITLE
Vim implementation

### ISSUE THREAD

**Issue by jacksonludwig** [earl-grey-theme/earl-grey#1]
Thanks for developing this theme.

I think it would be great to have a vim/neovim implementation for this. Would you feel comfortable with someone else working on it if there's nothing in the works right now?

**Comment by jacksonludwig** [comment]
FWIW, I started my own implementation [here](https://github.com/jacksonludwig/vim-earl-grey)

**Comment by JuneKelly** [comment]
Hi! Sorry, I never check my github notifications 😅 

Yes, I'm happy to see other implementations. If you feel the vim implementation is reasonably complete,  we could add a link to it from the website?

**Comment by jacksonludwig** [comment]
Sounds good to me. If someone finds an issue with it I'd be happy to look at it some more.

**Comment by JuneKelly** [comment]
Cool, I'll add a link to the site :+1:
